var MUSIC_DATA={
  "001.mp3": ["The Quarantine Zone", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "002.mp3": ["Smugglers", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "003.mp3": ["Never Again", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "004.mp3": ["Goodnight", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "005.mp3": ["I Know What You Are", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "006.mp3": ["Home", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "007.mp3": ["Infected", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "008.mp3": ["Aftermath", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "009.mp3": ["A New Dawn", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "010.mp3": ["No Escape", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "011.mp3": ["Childhood", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "012.mp3": ["The Path", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "013.mp3": ["Alone", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "014.mp3": ["Blackout", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "015.mp3": ["The Way It Was", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "016.mp3": ["Breathless", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "017.mp3": ["You And Me", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "018.mp3": ["The Outside", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "019.mp3": ["A New Beginning", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "020.mp3": ["The Hour", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "021.mp3": ["The Last Of Us", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "022.mp3": ["Forgotten Memories", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "023.mp3": ["The Outbreak", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "024.mp3": ["Innocence", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "025.mp3": ["By Any Means", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "026.mp3": ["The Choice", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "027.mp3": ["Vanishing Grace", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "028.mp3": ["The Hunters", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "029.mp3": ["Returning", "Gustavo Santaolalla", "The Last Of Us", ["Banda Sonora"], "TheLastOfUs.jpg" ],
  "030.mp3": ["Playground", "Bea Miller", "Arcane", ["Banda Sonora"], "arcane.jpeg"],
  "031.mp3": ["Dirty Little Animals", "Bones UK", "Arcane", ["Banda Sonora"], "arcane.jpeg"],
  "032.mp3": ["Our Love", "Curtis Harding", "Arcane", ["Banda Sonora"], "arcane.jpeg"],
  "033.mp3": ["Dynasties And Dystopia", "Denzel Curry", "Arcane", ["Banda Sonora"], "arcane.jpeg"],
  "034.mp3": ["When Everything Went Wrong", "Fantastic Negrito", "Arcane", ["Banda Sonora"], "arcane.jpeg"],
  "035.mp3": ["Enemy", "Imagine Dragons", "Arcane", ["Banda Sonora"], "Enemy.jpg"],
  "036.mp3": ["Misfit Toys", "Pusha T", "Arcane", ["Banda Sonora"], "missfits_toys.webp"],
  "037.mp3": ["Goodbye", "Ramsey", "Arcane", ["Banda Sonora"], "arcane.jpeg"],
  "038.mp3": ["What Could Have Been", "Sting", "Arcane", ["Banda Sonora"], "arcane.jpeg"],
  "039.mp3": ["Guns For Hire", "Woodkid", "Arcane", ["Banda Sonora"], "arcane.jpeg"],
  "040.mp3": ["Snakes", "Miyavi", "Arcane", ["Banda Sonora"], "Snakes.jpg"]
}